### PR TITLE
make DZG workaround more specific

### LINKED ISSUE #132: Odd readings from DWSB20.2TH: Display shows power -195W, vzlogger reports 460W
I'm not sure if *I'm* doing it wrong or the computers. In some situations the reported power matches what the display shows, but most often when I expect grid feed-in (and the meter display shows -195W, for example), vzlogger reports significant draw from the grid instead (460W, at roughly the same time).

dwsb_-195w

vzlogger configuration:
```json
{
  "retry": 0,
  "verbosity": 20,
  "log": "",
  "push": [],
  "local": {
    "enabled": true,
    "port": 8080,
    "index": true,
    "timeout": 0,
    "buffer": 0
  },
  "meters": [
    {
      "enabled": true,
      "allowskip": false,
      "interval": -1,
      "aggtime": -1,
      "aggfixedinterval": false,
      "channels": [
        {
          "api": "null",
          "uuid": "a61877f3-f289-4b7e-86f7-167b5fe07593",
          "identifier": "1-0:1.8.0"
        },
        {
          "api": "null",
          "uuid": "88ad4730-ee53-4236-8551-7daecc94f3a8",
          "identifier": "1-0:2.8.0"
        },
        {
          "api": "null",
          "uuid": "7ef5c3c6-92ae-44e7-a7c2-420cbad9b849",
          "identifier": "1-0:16.7.0"
        }
      ],
      "protocol": "sml",
      "device": "/dev/ttyUSB0",
      "pullseq": "",
      "baudrate": 9600,
      "parity": "8n1",
      "use_local_time": true
    }
  ]
}
```

Resulting JSON from the vzlogger web server:
```json
{
  "version": "0.8.1",
  "generator": "vzlogger",
  "data": [
    {
      "uuid": "a61877f3-f289-4b7e-86f7-167b5fe07593",
      "last": 1694350497673,
      "interval": -1,
      "protocol": "sml",
      "tuples": [
        [
          1694350497673,
          2897323.8000000003
        ]
      ]
    },
    {
      "uuid": "88ad4730-ee53-4236-8551-7daecc94f3a8",
      "last": 1694350497673,
      "interval": -1,
      "protocol": "sml",
      "tuples": [
        [
          1694350497673,
          163375.6
        ]
      ]
    },
    {
      "uuid": "7ef5c3c6-92ae-44e7-a7c2-420cbad9b849",
      "last": 1694350497673,
      "interval": -1,
      "protocol": "sml",
      "tuples": [
        [
          1694350497673,
          461.96000000000004
        ]
      ]
    }
  ]
}
```

The OBIS code should do the same thing as the display is showing, right? (As in: current power in/-output in Watts)
Am I holding it wrong or is there something else going on?

vzlogger is running in a docker container on Raspbian (Debian 11), built from `master`.

### PR DESCRIPTION
**Pull request by jmberg**
In #132 and volkszaehler/vzlogger#533 it was reported that there are DZG meters that fall into the range currently deemed broken (all DZG meters with serial numbers before 6000 0000), but aren't actually broken. The reason for this seemed to be that they're a different type than mine that was broken.

Further inquiry with DZG revealed that indeed only DVS74 meters are affected by the encoding issue, and then _those_ only for serial numbers before 6000 0000. They also said that (currently) the serial number ranges
 - 4200 0000 to 4899 9999, and
 - 5500 0000 to 5899 9999 are reserved for DVS74 meters.

As such, make the workaround detection more specific, and we no longer need to have the check for 6000 0000 either, just need to have a list of affected ranges. To achieve that, refactor the code into a separate function that actually decodes the serial number to an integer, so we can make the comparison more easily and have the list of affected numbers more clearly in the code.

This should fix #132 since the serial number there starts with 4005, so it's clearly not in the affected ranges, as explained by my contact at DZG. For volkszaehler/vzlogger#533 I don't have the serial number, but it's the same type of meter as in #132.

### CODE REVIEW

File: sml/src/sml_list.c [hunk 1]
```diff
@@ -112,16 +112,64 @@ sml_list *sml_list_init() {
 
 void sml_list_add(sml_list *list, sml_list *new_entry) { list->next = new_entry; }
 
+/* Note: this gets passed _every_ object found */
```
Comment (r00t-) [inline sml/src/sml_list.c:115]: "invoked for _every_ sml object encountered"?

("passed every object" can't be right because it's only passed a single object in each invocation,
 "found" can't be right because we don't search, we process/decode input...)

Comment (jmberg) [reply sml/src/sml_list.c:115]: yeah I guess

File: sml/src/sml_list.c [hunk 2]
```diff
@@ -112,16 +112,64 @@ sml_list *sml_list_init() {
...
+		    serial <= broken_dvs74_ranges[i].end)
+			return true;
+	}
+
+	return false;
+}
+
 struct workarounds {
-	unsigned int old_dzg_meter : 1;
+	unsigned int old_dzg_dvs74 : 1;
```
Comment (r00t-) [inline sml/src/sml_list.c:169]: i got confused vs. https://github.com/volkszaehler/libsml/pull/133 , i had not realized that the "workarounds" struct already existed before #133 ) :astonished:

File: sml/src/sml_list.c [hunk 3]
```diff
@@ -197,14 +246,9 @@ sml_list *sml_list_entry_parse(sml_buffer *buf, struct workarounds *workarounds)
...
-	if (l->obj_name && l->obj_name->len == sizeof(dzg_serial_name) &&
-		memcmp(l->obj_name->str, dzg_serial_name, sizeof(dzg_serial_name)) == 0 && l->value &&
-		l->value->type == SML_TYPE_OCTET_STRING &&
-		l->value->data.bytes->len >= (int)sizeof(dzg_serial_start) &&
-		memcmp(l->value->data.bytes->str, dzg_serial_start, sizeof(dzg_serial_start)) == 0 &&
-		memcmp(l->value->data.bytes->str, dzg_serial_fixed, sizeof(dzg_serial_fixed)) < 0) {
-		workarounds->old_dzg_meter = 1;
-	} else if (workarounds->old_dzg_meter && l->obj_name &&
+	if (detect_buggy_dzg_dvs74(l)) {
+		workarounds->old_dzg_dvs74 = 1;
```
Comment (r00t-) [inline sml/src/sml_list.c:250]: good thing to make this a function!

File: sml/src/sml_list.c [hunk 4]
```diff
@@ -172,8 +220,9 @@ sml_list *sml_list_entry_parse(sml_buffer *buf, struct workarounds *workarounds)
 		goto error;
 
 	/*
-	 * Work around DZG meters before serial numbers starting with
-	 * 6 (in decimal) - they encode the consumption wrongly:
+	 * Work around DZG DVS74 meters in the serial number ranges listed
+	 * in detect_buggy_dzg_dvs74() above - they encode the consumption
+	 * wrongly:
```
[the remark this answers is not in the document]
Comment (jmberg) [reply sml/src/sml_list.c:225]: heh yeah. you realize I'm just moving this though? ;-)

**Comment by r00t-** [comment]
can't test, but LGTM!

i'd leave you some time to address my comments (if you like), then i'd merge.

(we really want units-tests for this kind of stuff, but that's beyond the scope of this fix.)

**Comment by r00t-** [comment]
i haven't the slightest idea why github is refusing to run the workflow...
there is no way to run it manually.
i suggest you re-push occasionally to check if it's working again.

**Comment by jmberg** [comment]
It did eventually (after about an hour) show that I force-pushed, so it should be updated now.

File: sml/src/sml_list.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (r00t-) [reply sml/src/sml_list.c]: https://github.com/volkszaehler/libsml/commit/559ca1e3ff8de7645fc4372f632e42b64cec780f#r134001028 :grin:

**Comment by r00t-** [comment]
there's still no pipeline run and no option for me to run start one :\

**Comment by jmberg** [comment]
Looks better now, perhaps? I pushed a new version w/o any changes.

**Comment by r00t-** [comment]
> @jmberg jmberg force-pushed the dzg-dvs74 branch from 5ea032b to 49426e1 

https://github.com/volkszaehler/libsml/pull/136/checks
> make DZG workaround more specific 49426e1
> succeeded 9 hours ago in 17s

:tada:
